Responser
KrutNA/deeplay-lab-server pull request #5
Opened 2022-05-02 15:25 UTC by jjagorka

2022-05-04 10:08 UTC, MazaiSerg requested changes

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/CreateJson.java
> +    public static void createJson(ArrayList<Location> locations) throws Exception {
Лучше не завязываться на ArrayList. Лучше использовать List, или вообще Iterable

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/UnitSeating.java
> +    static Random rnd = new Random();
Почему все static? Это уже не про ооп, а про процедурное программирование

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/UnitSeating.java
> +    static public double predict(Location2 location2, List<Integer> position) {
Из названия класса здесь должны рассаживать юнитов, а в итоге тут почему то предсказатель

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/UnitSeating.java
> +    static public List<Seating> seatings(Location2 location2) {
Что за класс такой Location2?
Функции обычно называют действиями, а тут существительное

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/UnitSeating.java
> +            Location2 tempLocation = new Location2(location2.locationName(),tempOurUnits,location2.opponetsUnits(),location2.locateSize());
код стайл - пробелы после запятых. Может туда просто передать location целиком, а не кусками?

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/UnitSeating.java
> +            ArrayList<Integer> busyPosition = new ArrayList<>();
Busy имеет не совсем тот смысл. Тут больше подойдет occupied или booked

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/UnitSeating.java
> +record Location2(
Что за Locattion2????

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/UnitSeating.java
> +        List<OurUnit> opponetsUnits,
Может класс OurUnit стоит переименовать в Unit?

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/UnitSeating.java
> +        for (OurUnit i : location2.opponetsUnits()) {
i - это индекс. У тебя здесь скорее должен быть unit

2022-05-04 10:08 UTC, MazaiSerg commented on src/main/java/io/deeplay/lab/UnitSeating.java
> +        List<Integer> temp = new LinkedList<>();
С учетом того, что ты там обращаешься по индексу - точно нужен линкед лист?

2022-05-07 13:03 UTC, KrutNA commented
Closed because it was created by accident and all work is done on other branches.

2022-05-07 13:03 UTC, closed without merging